name: TaskManager CI

on:
  push:
    branches:
      - '*'

jobs:
  authenticate-git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  setup-java:
    runs-on: ubuntu-latest
    needs: authenticate-git
    outputs:
      java-home: ${{ steps.java.outputs.path }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        id: java
        uses: actions/setup-java@v3
        with:
          java-version: '22.0.2'
          distribution: 'temurin'

      - name: Cache Java Environment
        uses: actions/cache@v3
        with:
          path: ~/.java
          key: java-${{ runner.os }}-22.0.2
          restore-keys: |
            java-${{ runner.os }}-

  build:
    runs-on: ubuntu-latest
    needs: setup-java
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Java Cache
        uses: actions/cache@v3
        with:
          path: ~/.java
          key: java-${{ runner.os }}-22.0.2
          restore-keys: |
            java-${{ runner.os }}-

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Install Dependencies
        run: ./gradlew dependencies

      - name: Run Build
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Java Cache
        uses: actions/cache@v3
        with:
          path: ~/.java
          key: java-${{ runner.os }}-22.0.2
          restore-keys: |
            java-${{ runner.os }}-

      - name: Run Tests
        run: ./gradlew test
