name: TaskManager Mainline

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  setup-git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Development Branch
        run: git fetch origin development

  setup-java:
    runs-on: ubuntu-latest
    needs: setup-git
    outputs:
      java-home: ${{ steps.java.outputs.path }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        id: java
        uses: actions/setup-java@v3
        with:
          java-version: '22.0.2'
          distribution: 'temurin'

      - name: Cache Java Environment
        uses: actions/cache@v3
        with:
          path: ~/.java
          key: java-${{ runner.os }}-22.0.2
          restore-keys: |
            java-${{ runner.os }}-

  build:
    runs-on: ubuntu-latest
    needs: setup-java
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restore Java Cache
        uses: actions/cache@v3
        with:
          path: ~/.java
          key: java-${{ runner.os }}-22.0.2
          restore-keys: |
            java-${{ runner.os }}-

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Install Dependencies
        run: ./gradlew dependencies

      - name: Run Build
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restore Java Cache
        uses: actions/cache@v3
        with:
          path: ~/.java
          key: java-${{ runner.os }}-22.0.2
          restore-keys: |
            java-${{ runner.os }}-

      - name: Restore Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Run Tests
        run: ./gradlew test

  merge-development-into-main:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Development Branch
        run: git fetch origin development

      - name: Merge Development branch into Main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout main
          git pull origin main
          git merge --no-ff origin/development -m "GitHub Action: Merge development branch into main"
          git push origin main
